# Generated by Django 4.2.11 on 2026-07-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=150)),
                ('field_of_expertise', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age_years', models.IntegerField()),
                ('gender_identity', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=15)),
                ('phone_primary', models.CharField(max_length=20)),
                ('health_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('current_status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=15)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.medicalspecialist')),
                ('registered_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.patientrecord')),
            ],
        ),
    ]
