# Generated by Django 4.2.11 on 2026-07-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_medicalspecialist_user_auth_patientrecord_user_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('healthcare_tax', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('grand_total_payable', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Settled', 'Settled')], default='Unpaid', max_length=15)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('linked_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='appointments.bookingslot')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_observed', models.TextField()),
                ('prescribed_medication', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associated_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.bookingslot')),
            ],
        ),
    ]
